---
title: "Solution-3"
author: "Sanjeev Gadre"
date: "October 12, 2018"
output: md_document
---

```{r setup, include=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(magrittr)
library(readr)
```

This is the solution to the problem set found at https://www.r-exercises.com/2017/06/22/data-wrangling-reshaping/.

###3.1
```{r 3-1}
data = airquality[4:6]
str(data)
```

###3.2
```{r 3-2}
data %>% spread(Month,Temp) %>% head()
```

###3.3
```{r 3-3}
data %>% spread(Month,Temp) %>% gather(Month,Temp, 2:6) %>% head()
```

###3.4
```{r 3-4}
data %>% spread(Month,Temp) %>% gather(Month, Temp, "5","6","7","8","9") %>% head()
```

###3.5
```{r 3-5}
new.data = data %>% spread(Month,Temp) %>% gather(Month, Temp, -Day)
```

###3.6
```{r 3-6}
new.data %>% unite(Date, Day, Month, sep="-") %>% head()
```

###3.7
```{r 3-7}
new.data = new.data %>% unite(Date, Day, Month, sep="-") %>% 
  separate(Date, c("Day","Month"), sep="-")
```

###3.8
```{r 3-8}
new.data %>% replace_na(list(Temp = "Unknown")) %>% tail()
```

###3.9
```{r 3-9}
new.data$year = rep(NA, nrow(new.data))
new.data$year[1] = '2015'
new.data$year[as.integer(nrow(new.data)/3)] = '2016'
new.data$year[as.integer(2*nrow(new.data)/3)] = '2017'

new.data = new.data %>% fill(year, .direction="down")

```

###3.10
```{r 3-10}
parse_number(new.data$Temp, na="NA")
```

